openapi: 3.0.0
info:
  title: Pet API
  version: 1.0.0
  description: API for managing pets

paths:
  /pet.php:
    get:
      summary: Get pet(s)
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: false
          description: Pet ID to fetch a single pet
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Pet'
                  - type: array
                    items:
                      $ref: '#/components/schemas/Pet'
    post:
      summary: Create a new pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInput'
      responses:
        '200':
          description: Pet created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    put:
      summary: Update a pet
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: Pet ID to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInput'
      responses:
        '200':
          description: Pet updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Missing id
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    delete:
      summary: Delete a pet (soft or hard)
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: Pet ID to delete
        - in: query
          name: force
          schema:
            type: string
            enum: [true]
          required: false
          description: Set to true for hard delete
      responses:
        '200':
          description: Pet deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Missing id
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        year_of_birth:
          type: integer
        color:
          type: string
        weight:
          type: number
          format: float
        gender:
          type: string
        is_spayed_neutered:
          type: boolean
        description:
          type: string
        owner_id:
          type: integer
        animal_type_id:
          type: integer
        animal_breed_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true
    PetInput:
      type: object
      required:
        - name
        - year_of_birth
        - color
        - weight
        - gender
        - is_spayed_neutered
        - description
        - owner_id
        - animal_type_id
        - animal_breed_id
      properties:
        name:
          type: string
        year_of_birth:
          type: integer
        color:
          type: string
        weight:
          type: number
          format: float
        gender:
          type: string
        is_spayed_neutered:
          type: boolean
        description:
          type: string
        owner_id:
          type: integer
        animal_type_id:
          type: integer
        animal_breed_id:
          type: integer
